#source 'https://rubygems.org'
#gem 'jquery_gantt_rails'
#gem 'google_calendar_api_v2'
#gem "google_calendar_oauth2"
#gem 'ruby-haml-js'
#gem 'google_oauth_calendar' , :github => 'deafgreatdane/google_oauth_calendar'
#gem 'google_calendar_api_oauth2', '0.0.2', :git => 'https://github.com/nightweb/google_calendar_api_oauth2.git'
#gem 'erb2haml'
#gem 'rubyzip', '= 0.9.9'
#gem 'websocket', '= 1.0.7'
#gem 'selenium-webdriver', '= 2.35.1'
#gem 'xpath', '= 1.0.0'
#gem 'capybara', '~> 2.0.0'

gem 'gcal4ruby', :git => 'https://github.com/SeabourneConsulting/GCal4Ruby.git'
gem 'google-api-client'